server:
  port: 1876

spring:
  application:
    name: yundemo
  profiles:
    active: dev #默认为开发环境
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      # 主库数据源
      master:
        url: jdbc:mysql://114.116.25.184:3306/yun_data?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
        username: root
        password: Zyb@940729
      # 从库数据源
      slave:
        # 从数据源开关/默认关闭
        enabled: true
        url: jdbc:mysql://114.116.25.184:3306/yun_data2?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
        username: root
        password: Zyb@940729
      # 初始连接数
      initialSize: 5
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      webStatFilter:
        enabled: true
      statViewServlet:
        enabled: true
        # 设置白名单，不填则允许所有访问
        allow:
        url-pattern: /druid/*
        # 控制台管理用户名和密码
        login-username: ruoyi
        login-password: 123456
      filter:
        stat:
          enabled: true
          # 慢SQL记录
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    # 开启发送者confirm机制
    publisher-confirm-type: correlated
    # 开启发送者消息抵达队列的确认机制
    publisher-returns: true
    template:
      # 只要消息未能抵达队列 就触发失败回调
      mandatory: true
    listener:
      direct:
        acknowledge-mode: manual
      simple:
        #手动确认消费
        acknowledge-mode: manual
        retry:
          # 开启消费者重试机制（默认就是true，false则取消重试机制）
          enabled: true
          # 最大重试次数
          max-attempts: 5
          # 重试间距（单位：秒）
          initial-interval: 2s

# MyBatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.yun.admin.model.pojo
  #typeAliasesPackage:com.yun.admin.model.pojo
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml


# minio 文件存储配置信息
minio:
  minioUrl: http://114.116.25.184:9000/
  accessKey: minioadmin
  secretKey: minioadmin
  passagerBucket: passager
  driverBucket: driver
  systemBucket: system
  minyunBucket: minyun
  downLoadPath: /data/minIo/tmp/downLoad

notice:
  ####### 企业微信群机器人key
  wechat-key: xxxxxxxxx-xxx-xxx-xxxx-xxxxxxxxxx
  ####### 需要@的群成员手机号
  phone-list:
## 轻量级HTTP客户端框架forest
forest:
  # 配置底层API为 okhttp3
  backend: okhttp3
  # 连接池最大连接数，默认值为500
  max-connections: 1000
  # 每个路由的最大连接数，默认值为500
  max-route-connections: 500
  # 请求超时时间，单位为毫秒, 默认值为3000
  timeout: 3000
  # 连接超时时间，单位为毫秒, 默认值为2000
  connect-timeout: 3000
  # 请求失败后重试次数，默认为0次不重试
  retry-count: 1
  # 单向验证的HTTPS的默认SSL协议，默认为SSLv3
  ssl-protocol: SSLv3
  # 打开或关闭日志，默认为true
  logEnabled: true
  # 打开/关闭Forest请求日志（默认为 true）
  log-request: true
  # 打开/关闭Forest响应状态日志（默认为 true）
  log-response-status: true
  # 打开/关闭Forest响应内容日志（默认为 false）
  log-response-content: true
